---
- name: Install base packages and set environment variables
  ansible.builtin.import_playbook: playbooks/install_prerequisites.yml

- name: Configure chronyd
  ansible.builtin.import_playbook: playbooks/configure_chronyd.yml

- name: Configure Bash profile
  ansible.builtin.import_playbook: playbooks/configure_bash.yml

- name: Configure logging
  ansible.builtin.import_playbook: playbooks/configure_logging.yml

- name: Cleanup
  ansible.builtin.import_playbook: playbooks/cleanup.yml
