- name: Create Policies Organizational Unit (OU) Base DN
  community.general.ldap_entry:
    dn: "{{ policies_dn }}"
    objectClass:
      - organizationalUnit
    attributes:
      ou: Policies

- name: Create Password policy entry
  community.general.ldap_entry:
    dn: "cn=passwordDefault,{{ policies_dn }}"
    objectClass:
      - organizationalRole
      - pwdPolicy
      - pwdPolicyChecker
    attributes: "{{ ldap_ppolicy_attrs }}"
    server_uri: "{{ ldap_server_uri }}"
    bind_dn: "{{ bind_dn }}"
    bind_pw: "{{ vault_ldap_bind_pw }}"
    state: present
  no_log: true
