- name: Install required packages
  ansible.builtin.dnf:
    name:
      - openldap
      - openldap-servers
      - openldap-clients
      - cyrus-sasl-lib
    state: present
    validate_certs: true
    disable_gpg_check: false

- name: Install python-ldap development packages
  ansible.builtin.dnf:
    name:
      - gcc
      - "python{{ ansible_facts['python'].version.major }}.{{ ansible_facts['python'].version.minor }}-devel"
      - openldap-devel
    state: present

- name: Install python-ldap
  ansible.builtin.command:
    argv:
      - "{{ ansible_facts['python'].executable }}"
      - -m
      - pip
      - install
      - python-ldap
  changed_when: false

- name: Verify python-ldap is available to Ansible Python
  ansible.builtin.command:
    argv:
      - "{{ ansible_facts['python'].executable }}"
      - -c
      - 'import ldap; print(ldap.__version__)'
  changed_when: false

- name: Enable and start slapd
  ansible.builtin.systemd_service:
    name: slapd.service
    enabled: true
    state: started
