- name: Install ldap packages
  ansible.builtin.import_tasks: install.yml

- name: Configure ldap
  ansible.builtin.import_tasks: configure.yml

- name: Validate ldap configurations
  ansible.builtin.import_tasks: validate.yml

- name: Configure listener hardening drop-in
  ansible.builtin.import_tasks: configure_listener_hardening.yml
