- name: Gather Ansible facts
  ansible.builtin.setup:
    filter:
      - architecture
      - date_time
      - default_ipv4
      - distribution
      - distribution_major_version
      - fips
      - os_family
      - python_version
      - selinux
      - system
      - user_id

- name: Show OS facts
  ansible.builtin.debug:
    msg:
      - "Date and time: {{ ansible_facts['date_time'].date }}"
      - "Ansible user: {{ ansible_facts['user_id'] }}"
      - "Distro: {{ ansible_facts['distribution'] }} version: {{ ansible_distribution_major_version }}"
      - "Python version: {{ ansible_facts['python_version'] }}"
      - "OS family: {{ ansible_facts['os_family'] }}"
      - "System: {{ ansible_facts['system'] }}"
      - "Architecture: {{ ansible_facts['architecture'] }}"
      - "FIPS boolean: {{ ansible_facts['fips'] }}"
      - "SELinux status: {{ ansible_facts['selinux'].status }}"
      - "Ansible default IPV4: {{ ansible_facts['default_ipv4'].address }} {{ ansible_facts['default_ipv4'].interface }}"

# - name: Set normalized build architecture
#   ansible.builtin.set_fact:
#     os_arch: >-
#       {{
#         {
#           'x86_64': 'linux_amd64',
#           'aarch64': 'linux_arm64'
#         }[ansible_facts['architecture']]
#       }}

# - name: Show os_arch variable
#   ansible.builtin.debug:
#     var: os_arch

# TODO set Cert and Remote State S3 bucket prefix

- name: Set base domain
  ansible.builtin.set_fact:
    base_domain: "{{ lookup('template', 'templates/base_domain.yml.j2') | trim }}"

- name: Show base_domain variable
  ansible.builtin.debug:
    var: base_domain

- name: Fail if account ID is not recognized
  ansible.builtin.fail:
    msg: >-
      Unknown AWS account ID: {{ aws_account_id_current }}.
  when: base_domain == ''
