ssh_port: 22
# add '::' to include IPv6 address
ssh_listen_addresses:
  - '0.0.0.0'
# set to 'any' to include IPv6 family
ssh_address_family: inet

ssh_authentication_methods:
  - publickey

ssh_host_keys:
  - "/etc/ssh/ssh_host_ecdsa_key"
  - "/etc/ssh/ssh_host_rsa_key"

ssh_authorized_keys_command: "/usr/bin/timeout 5s /usr/local/bin/ssh-keyldap %u %f"
ssh_authorized_keys_command_user: nobody

ssh_syslog_facility: AUTHPRIV
# QUIET, FATAL, ERROR, INFO, VERBOSE, DEBUG, DEBUG1, DEBUG2,DEBUG3
ssh_log_level: INFO

ssh_rekey_limit:
  - 1G
  - 1h
ssh_client_alive_interval: 300
ssh_client_alive_count_max: 2

ssh_client_alive_count_max_packer: 0

ssh_login_grace_time: 60
ssh_max_auth_tries: 3
ssh_max_sessions: 3
ssh_max_startups: "10:30:60"

ssh_accept_env:
  - LANG
  - LANGUAGE
  - LC_*
