- name: Install OpenSCAP tools
  ansible.builtin.dnf:
    name: "{{ item }}"
    disable_gpg_check: false
    state: present
  loop:
    - openscap-scanner
    - openscap-utils
    - scap-security-guide
