- name: Remove AWS CLI installation files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/tmp/{{ aws_cli_gpg_key }}"
    - "/tmp/{{ aws_cli_installer }}.zip"
    - "/tmp/{{ aws_cli_installer }}.sig"
    - /tmp/aws

- name: Remove AWS SSM Agent installation files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/tmp/{{ aws_ssm_agent_gpg_key }}"
    - "/tmp/{{ aws_ssm_agent_package }}"
    - "/tmp/{{ aws_ssm_agent_package }}.sig"
