# https://docs.ansible.com/projects/ansible/latest/collections/amazon/aws/ec2_metadata_facts_module.html
- name: Gather EC2 metadata facts
  amazon.aws.ec2_metadata_facts:

- name: Set AWS region
  ansible.builtin.set_fact:
    aws_region: "{{ ansible_facts['ec2_placement_region'] }}"

- name: Show aws_region variable
  ansible.builtin.debug:
    var: aws_region

- name: Set AWS Instance ID
  ansible.builtin.set_fact:
    aws_instance_id: "{{ ansible_facts['ec2_instance_identity_document_instanceid'] }}"

- name: Show aws_instance_id variable
  ansible.builtin.debug:
    var: aws_instance_id

- name: Set current AWS account id
  ansible.builtin.set_fact:
    aws_account_id_current: "{{ ansible_facts['ec2_instance_identity_document_accountid'] }}"

- name: Show aws_account_id_current variable
  ansible.builtin.debug:
    var: aws_account_id_current
