- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Start nm-cloud-setup service and ensure enabled at boot
  ansible.builtin.systemd_service:
    name: nm-cloud-setup.service
    state: started
    enabled: true
  tags:
    - aws
    - nm-cloud-setup

- name: Start nm-cloud-setup timer and ensure enabled at boot
  ansible.builtin.systemd_service:
    name: nm-cloud-setup.timer
    state: started
    enabled: true
  tags:
    - nm-cloud-setup
    - chron
