[Service]
# TCP IPv4 loopback and local Unix-domain socket only.
Environment="SLAPD_URLS=ldap://127.0.0.1 ldapi:///"

# Reset the vendor ExecStart, which listens on all interfaces.
ExecStart=
ExecStart=/usr/sbin/slapd -u ldap -h $SLAPD_URLS
