---
- name: Cleanup build artifacts
  hosts: local_host
  become: true

  tasks:
    - name: Cleanup AWS
      ansible.builtin.import_role:
        name: aws
        tasks_from: cleanup

    - name: Cleanup logs
      ansible.builtin.import_role:
        name: logs
        tasks_from: cleanup

    - name: Cleanup OpenSCAP scan files
      ansible.builtin.import_role:
        name: openscap
        tasks_from: cleanup
