---
- name: Install required packages for base AMI
  hosts: local_host
  become: true

  tasks:
    # global variable necessary for version-specific package repos
    - name: Gather Ansible OS distribution major version
      ansible.builtin.setup:
        filter:
          - distribution_major_version

    - name: Set RHEL major version
      ansible.builtin.set_fact:
        rhel_version: "{{ ansible_facts['distribution_major_version'] }}"

    - name: Show rhel_version variable
      ansible.builtin.debug:
        var: rhel_version

    # TASKS
    - name: Install base packages
      ansible.builtin.import_role:
        name: base_packages
        tasks_from: install_base_packages

    - name: Install AWS CLI v2
      ansible.builtin.import_role:
        name: aws
        tasks_from: install_aws_cli

    # set AWS environment variables (aws_region, aws_account_id_current, ...)
    - name: Fetch AWS environment facts
      ansible.builtin.import_role:
        name: aws
        tasks_from: fetch_aws_ec2_metadata_facts.yml

    # set project environment variables (base_domain, rhel_version, ...)
    - name: Initialize build environment
      ansible.builtin.import_tasks: ../tasks/initialize_environment.yml

    - name: Install SSM Agent
      ansible.builtin.import_role:
        name: aws
        tasks_from: install_ssm_agent

    - name: Generate RPM manifest
      ansible.builtin.import_role:
        name: base_packages
        tasks_from: generate_rpm_manifest
